### ISSUE TITLE
Add matcher for response headers

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#100]
It would be convenient to have matcher for response header similar to `RsHasStatus` and `RsHasBody`.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/http#100` is not assigned, can't get performer

**Comment by olegmoz** [comment]
@g4s8 could you please make a release with this issue resolved?
