### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#102]
HTTP module should provide some common ways of logging, so it won't be replicated in adapters & Artipie core.

**Comment by olegmoz** [comment]
@g4s8 please make a release with this issue

**Comment by g4s8** [comment]
@rultor release, tag=`0.7.3`

**Comment by Guseyn** [comment]
@g4s8 could you please close completed tickets.

**Comment by 0crat** [comment]
Job `gh:artipie/http#102` is not assigned, can't get performer
