### ISSUE TITLE
Support for 204 and 416 HTTP response status codes and PATCH method

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#106]
These statuses are not present in RsStatus, but needed to implement pushing an image in Docker regitsry, see https://docs.docker.com/registry/spec/api/#pushing-an-image

**Comment by olegmoz** [comment]
PATCH method is also required and does not present in HTTP

**Comment by olegmoz** [comment]
@g4s8 could you please release HTTP with this issue? All of this will soon be needed in Docker adapter.

**Comment by 0crat** [comment]
Job `gh:artipie/http#106` is not assigned, can't get performer

**Comment by g4s8** [comment]
@rultor release, tag=`0.7.4`
