### ISSUE TITLE
TkRequest.java:79-81: Add a unit test to verify cancel...

### ISSUE THREAD

**Issue by 0pdd** [artipie/http#11]
The puzzle `7-5352e0ad` from #7 has to be resolved: 

https://github.com/artipie/http/blob/4090c033cc8503b74c0ae8ba7ffebd9d71e06f6d/src/main/java/com/artipie/http/tk/TkRequest.java#L79-L81

The puzzle was created by @g4s8 on 04-Feb-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `7-5352e0ad` has disappeared from the source code, that's why I closed this issue.
