### ISSUE TITLE
Routing example in readme

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/http#110]
Routing example in readme file seems to be outdated:
- `RtRule.ByMethod` ctor now except `RqMethod` itself, not string
- `SliceSimple` ctor signature was also changed
- `SliceRoute.FALLBACK` does not exists
- `Slice.Wrap` excepts only one `Slice`, not many

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@olenagerasimova thanks ,fixed: https://github.com/artipie/http/commit/6aeca62485b2181af3b8904c2058bb0e4bd60780

**Comment by 0crat** [comment]
Job [#110](https://github.com/artipie/http/issues/110) is closed, can't start order

**Comment by 0crat** [comment]
Job `gh:artipie/http#110` is not assigned, can't get performer
