### ISSUE TITLE
Slice to cut initial part of URI path

### ISSUE THREAD

**Issue by g4s8** [artipie/http#115]
Create `Slice` implementation to remove initial part from URI, it will be used by `artipie/artipie` to hide repository routing from repository implementations. The slice should patch request line and remove initial part from URI path, e.g. this request line:
```http
GET http://www.w3.org/pub/WWW/TheProject.html HTTP/1.1
```
should be patched to this:
```http
GET http://www.w3.org/WWW/TheProject.html HTTP/1.1
```

**Comment by 0crat** [comment]
The job [#115](https://github.com/artipie/http/issues/115) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/dcf47dd7-f572-4020-a57a-83b64fa64cb6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@0crat wait for #116 review

**Comment by ammaratef45** [comment]
@g4s8 now the PR is merged this should be closed?

**Comment by g4s8** [comment]
@ammaratef45 thanks

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
