### ISSUE TITLE
`LoggingSlice` - use origin slice as logger

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/http#118]
Let's make small correction in `LoggingSlice` to use origin slice as logger (source). Thus is would be possible to easily filter logs by origin. 

This issue was born [here](https://github.com/artipie/npm-proxy-adapter/pull/1/files/a2cf22fe84ae03d008c6af43c95d6d2acada2823#r408256317).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
resolved in #126
