### ISSUE TITLE
Add header matcher

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#120]
It is quite common it tests to check headers coming from slice. There is no convenient matcher for it in Hamcrest out of the box or in our library

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by olegmoz** [comment]
@g4s8 could you please make a new release with recent changes in HTTP?

**Comment by 0crat** [comment]
Job `gh:artipie/http#120` is not assigned, can't get performer
