### ISSUE TITLE
Headers abstarction

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#122]
HTTP headers are represented by type `Iterable<Map.Entry<String, String>>`. This is very verbose  type description and it would be better to have at least an alias and a point for possible future extension (ex. find all header values with same name, find header value with case-insensitive name)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/http#122` is not assigned, can't get performer
