### ISSUE TITLE
Extract interface from SliceRoute.Path

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/http#127]
Let's say our adapter external http api excepts `get` requests on different endpoint, each endpoint does different job, so we have a `Slice` implementation per endpoint. Then we will have to set routes  somewhere like this:
```java
    new SliceRoute(
            new SliceRoute.Path(
                new RtRule.Multiple(
                    new RtRule.ByPath(Pattern.compile(".+/@v/v.*\\.info .+")),
                    new RtRule.ByMethod(RqMethod.GET)
                ),
                new LoggingSlice(new InfoSlice())
            ),
            new SliceRoute.Path(
                new RtRule.Multiple(
                    new RtRule.ByPath(Pattern.compile(".+/@v/v.*\\.mod .+")),
                    new RtRule.ByMethod(RqMethod.GET)
                ),
                new LoggingSlice(new ModSlice())
            ),
            //etceteras
            new SliceRoute.Path(
                RtRule.FALLBACK,
                new SliceSimple(
                    new RsWithStatus(RsStatus.NOT_FOUND)
                )
            )
    )
```
If `Path` would've been an interface, we could create `GetPath` implementation that would take pattern and a slice as arguments and encapsulate all the `RtRule` instantiation and make the code less verbose.

Origin of the idea is [this](https://github.com/artipie/go-adapter/pull/29#discussion_r410687189) comment by @Vatavuk from CR in go-adapter.

**Comment by g4s8** [comment]
@olenagerasimova yes it makes sense

**Comment by g4s8** [comment]
@0crat assign @marceloamadeu

**Comment by 0crat** [comment]
> @0crat assign @marceloamadeu  ([here](https://github.com/artipie/http/issues/127#issuecomment-630217980))

@g4s8 The job [#127](https://github.com/artipie/http/issues/127) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/ea3e9228-9c95-4469-b247-7ed3af1e1f16); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat assign @victornoel

**Comment by 0crat** [comment]
> @0crat assign @victornoel  ([here](https://github.com/artipie/http/issues/127#issuecomment-633649975))

@g4s8 The job [#127](https://github.com/artipie/http/issues/127) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/84ac155e-289b-43ab-8c3f-e2d46f5566d5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by marceloamadeu** [comment]
@0crat wait
@g4s8 How do I delete this issue from my agenda since it is now with @victornoel ?
Tks

**Comment by 0crat** [comment]
> @0crat wait @g4s8 How do I delete this issue from my agenda? It is now with @victornoel? Tks ([here](https://github.com/artipie/http/issues/127#issuecomment-634392149))

@marceloamadeu @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) you can't register impediment for this job

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/http/issues/127#issuecomment-634455042))

@g4s8 This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#127](https://github.com/artipie/http/issues/127) is [in scope](http://www.zerocracy.com/policy.html#14) for 2days
  * The role is `DEV`
  * The job is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel) for [2days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @victornoel[/z](https://www.0crat.com/u/victornoel) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fhttp%23127%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@0crat assign @victornoel

**Comment by 0crat** [comment]
> @0crat assign @victornoel  ([here](https://github.com/artipie/http/issues/127#issuecomment-634653800))

@g4s8 The job [#127](https://github.com/artipie/http/issues/127) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/c0867338-6512-423f-bb04-3918df376837); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
> @0crat assign @victornoel  ([here](https://github.com/artipie/http/issues/127#issuecomment-634653800))

@g4s8 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@a6481982-e24c-4d53-86e7-af311f6ddbe6, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:artipie/http#127] declared for identity constraint of element "agenda".
```

[0.53.14](https://github.com/zerocracy/farm): CID: [3cbe2c5e-ef86-497d-8c5b-b2dd0d5bf00d](https://www.0crat.com/footprint/CT2E6TK9B/3cbe2c5e-ef86-497d-8c5b-b2dd0d5bf00d), Type: "Order was given"

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/http/issues/127#issuecomment-634658303))

@g4s8 This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#127](https://github.com/artipie/http/issues/127) is [in scope](http://www.zerocracy.com/policy.html#14) for 25min
  * The role is `DEV`
  * The job is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel) for [25min](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @victornoel[/z](https://www.0crat.com/u/victornoel) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fhttp%23127%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@0crat wait for #166

**Comment by victornoel** [comment]
@olenagerasimova this has been merged, can we close this issue?

**Comment by olenagerasimova** [comment]
@victornoel sure, thanks

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
The job [#127](https://github.com/artipie/http/issues/127) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/2a6658ee-bc8d-4c00-9466-7d82ae1a42f7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/http/issues/127#issuecomment-639991415))

@victornoel This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#127](https://github.com/artipie/http/issues/127) is [in scope](http://www.zerocracy.com/policy.html#14) for 10days
  * The role is `DEV`
  * The job is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel) for [8hr](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @victornoel[/z](https://www.0crat.com/u/victornoel) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fhttp%23127%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@g4s8 0crat incorrectly reassigned this job

**Comment by victornoel** [comment]
@g4s8 can you do something? if I refuse I will be penalized and also someone else will get reassigned...

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat refuse

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/http/issues/127#issuecomment-642456463))

@g4s8 Job `gh:artipie/http#127` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/http/issues/127#issuecomment-642456489))

@g4s8 Job `gh:artipie/http#127` is not assigned, can't get performer
