### ISSUE TITLE
RsHasHeaders does not work

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/http#129]
`RsHasHeaders` does not seem to work properly, please, let's check it. Response in my case is created like this
```
    new RsWithHeaders(
            this.origin.response(line, headers, body),
            new ListOf<Map.Entry<String, String>>(
                new MapEntry<>("content-type", "application/zip")
            )
    )
```
where origin is a `DownloadSlice`.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
My bad, `RsHasHeaders` works just file.

**Comment by 0crat** [comment]
Job `gh:artipie/http#129` is not assigned, can't get performer
