### ISSUE TITLE
Header class is missing

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#131]
Headers in the module are represented by `Map.Entry` interface, yet there is no implementation neither in this module nor in standard Java Runtime library.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by olegmoz** [comment]
@g4s8 could you please make a new release of HTTP module?

**Comment by g4s8** [comment]
@rultor release, tag=`0.8.2`
