### ISSUE TITLE
Add headers to SliceDownload

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/http#132]
I'd suggest adding headers (or just content-type) to `SliceDownload`, would be very handy at least in go-adapter.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@olenagerasimova how do you suggest determining mime types of binaries? By file magic or somehow else?

**Comment by Sammers21** [comment]
Can content-type be inferred from the file extension?

**Comment by olenagerasimova** [comment]
@g4s8 @Sammers21 no magic or determining content-type from extension, I was thinking simply about adding new field to the class: either list of headers or string for content-type. 
Or we can create new decorator for `Slice` to add headers, `SliceWithHeaders`.

**Comment by g4s8** [comment]
@rultor release, tag=`0.8.3`
