### ISSUE TITLE
Make BasicIdentities accessable from other packages

### ISSUE THREAD

**Issue by IlyaMoskva** [artipie/http#137]
For cases when artipie doesn't know about identity mechanism.
Need to be solved for https://github.com/artipie/files-adapter/issues/13

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@rultor release, tag=`0.8.4`

**Comment by g4s8** [comment]
@rultor release, tag=`0.8.4`

**Comment by g4s8** [comment]
@rultor release, tag=`0.8.4`

**Comment by olegmoz** [comment]
`BasicIdentities` is a public class now, the issue is resolved

**Comment by 0crat** [comment]
Job `gh:artipie/http#137` is not assigned, can't get performer
