### ISSUE TITLE
Missing abstract decorator for `Header`

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#141]
There is no abstract decorator for building custom headers, it would be nice to have Header.Wrap to create new header classes by composition

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/http#141` is not assigned, can't get performer

**Comment by olegmoz** [comment]
@g4s8 could you please release HTTP with this issue fixed?

**Comment by g4s8** [comment]
@rultor release, tag=`0.8.5`

**Comment by olegmoz** [comment]
release, tag=`0.8.7`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.8.7`
