### ISSUE TITLE
Add a SliceDelete

### ISSUE THREAD

**Issue by victornoel** [artipie/http#148]
We need a `SliceDelete` that removes a key from a storage.

We also need to define what will be the corresponding permission for using it, I propose `delete` or `remove`.

This is needed for artipie/files-adapter#15

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@victornoel yes, it's better to implement this slice in `artipie/http` module. But permission names are related to repository itself, not to http. You can use authorization mechanism from this module in maven repo:
```java
new SliceAuth(
    new SliceDelete(storage),
    new Permission.ByName("delete", perms),
    users
)
```

**Comment by 0crat** [comment]
The job [#148](https://github.com/artipie/http/issues/148) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/ba5af437-1b17-4a83-ab32-275a2f314693); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for #173

**Comment by 0crat** [comment]
The project doesn't have enough funds, can't make a payment
