### ISSUE TITLE
`LoggingSlice` should log errors

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#149]
If exception is thrown on attempt to handle request by slice `LoggingSlice` does not log anything. This makes it hard to understand problems in faulty slices. It should be logging exceptions as it logs success responses.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/http#149` is not assigned, can't get performer

**Comment by olegmoz** [comment]
@rultor release, tag=`0.9.4`
