### ISSUE TITLE
Authentication should report the result

### ISSUE THREAD

**Issue by g4s8** [artipie/http#151]
`Authentication` has method `verify` which returns void. We need to use the result to determinate does credentials are valid or not

**Comment by 0crat** [comment]
The job [#151](https://github.com/artipie/http/issues/151) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/44d4e814-fb22-46f7-a7d7-49780eb79db7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.9`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6a7d3b7d-e954-434c-b310-3a88a3cd41df, thread: pool-1866-thread-1
com.zerocracy.radars.github.ReSafe[81] java.io.IOException: java.lang.OutOfMemoryError: unable to create new native thread
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[0.53.14](https://github.com/zerocracy/farm): Issue: artipie/http#151, Action: `created`

**Comment by g4s8** [comment]
@rultor release, tag=`0.9.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.9.2`

**Comment by g4s8** [comment]
Done

**Comment by 0crat** [comment]
Job `gh:artipie/http#151` is not assigned, can't get performer
