### ISSUE TITLE
Create `ResponseMatcher` to avoid code duplication

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/http#153]
While testing slices we have a lot of code like this:
```
            new AllOf<>(
                Arrays.asList(
                    new RsHasStatus(RsStatus.ACCEPTED),
                    new RsHasHeaders(
                        new Header("Location", path),
                        new Header("Range", String.format("0-%d", data.length - 1))
                    //...
                    )
                )
            )
``` 
Let's create `ResponseMatcher` class to avoid duplications. This class can extend `AllOf<>` matcher and have a lot of ctors: with status, with status and headers, with status and body, maybe even empty (status 200 by default) and so on. Something like this:
```
final class ResponseMatcher extends AllOf<Response> {

        public ResponseMatcher(final RsStatus status) {
            super(
                new ListOf<Matcher<? super Response>>(
                    new RsHasStatus(status)
                )
            );
        }
}
```
Having this class will allow us to get rid of constant creations `AllOf<>(ListOf<>(...))`.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#153](https://github.com/artipie/http/issues/153) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/6c245217-82a1-4f63-acf6-bf8200b3a5a2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:artipie/http#153` is not assigned, can't get performer
