### ISSUE TITLE
`AuthSlice` unauthorized response missing `WWW-Authenticate` header

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#156]
Server should respond with 401 status and `WWW-Authenticate` header if requied authentication header is missing from response. This is by RFC, see https://tools.ietf.org/html/rfc7235#section-4.1
This behavior is expected by NuGet client

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by olegmoz** [comment]
@rultor release, tag=`0.9.3`

**Comment by olegmoz** [comment]
@g4s8 there is a problem with releasing http module via rultor, could you please look into this?

**Comment by 0crat** [comment]
Job `gh:artipie/http#156` is not assigned, can't get performer

**Comment by olegmoz** [comment]
@rultor release, tag=`0.9.3`
