### ISSUE TITLE
Add `BasicAuthorizationHeader`

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#161]
It would be very helpful to have a way to create `Authorization` header for Basic auth in tests.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by olegmoz** [comment]
@rultor release, tag=`0.9.5`

**Comment by 0crat** [comment]
Job `gh:artipie/http#161` is not assigned, can't get performer
