### ISSUE TITLE
Hide specified path instead of first segment

### ISSUE THREAD

**Issue by g4s8** [artipie/http#163]
Let's change implementation of `HiddenRouteSlice` to hide the provided path instead of first.

**Comment by 0crat** [comment]
The job [#163](https://github.com/artipie/http/issues/163) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f56c3664-64d9-419a-8944-2aa0331cb276); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by olegmoz** [comment]
@rultor release, tag=`0.9.6`

**Comment by g4s8** [comment]
Fixed
