### ISSUE TITLE
Implement group slice

### ISSUE THREAD

**Issue by brastak** [artipie/http#169]
### Motivation
Group repositories is critical part for successful implementation of full-featured repository management system. It provides a single access point for different kind of concrete repo types: customer can combine several hosted and proxy repositories with single endpoint.

### Implementation details
**http** module: implement `GroupSlice` that get List of underlying Slices in constructor. When `GroupSlice` handle requests, it calls in parallel all slices in the list. The first HTTP 200 response will be returned. Otherwise, the first HTTP 30X, then the first HTTP 40X and then the first 50X.
Group Slice can be configured to handle only specific HTTP methods. By default, it will handle only `HTTP GET` (subject to discuss - we can add `HTTP HEAD` or other "read" methods if they are used by repos). But Group Slice can be configured to handle other request methods with auxiliary constructor. There is no any logic based on underlying slices - all of them will receive the same request or will not at all.

**concrete group adapter** module: in most cases, we can use `GroupSlice` directly. But sometimes it is not enough. 
In this case, the first option is to use `ConcreteGroupSlice` approach. Developer creates separate module `<tool>-group-adapter` and implements a decorator for `GroupSlice`. It allows to re-use `GroupSlice` logic, but change the input or output for Slice. Group adapter for NPM can be implemented this way.
The second option is to implement your own Group Slice. This approach can be used when protocol details do useless base `GroupSlice` logic. Currently, I can not give any example for this case.

**artipie** module: implement instantiation in `SliceFromConfig`. I suggest to keep type separation here - `mvn` group repo and `npm` group repo should have different types (`mvn-group` and `npm-group`, for example). Even if the result will be simple `GroupSlice`. It allows us to verify group repo config. When `SliceFromConfig` instantiates group repo, it parses the config and instantiates all required repos. If any of them could not be found, it is handled the same way as original repo could not be found.

### The responsibility
* `GroupSlice` knows about underlying Slices, resend original request for them and handles responses.
* `ConcreteGroupSlice` knows protocol details and can modify requests and responses to `GroupSlice`.
* `SliceFromConfig` knows `group` repo types and can instantiate the `GroupSlice` and `ConcreteGroupSlice` the proper way.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by brastak** [comment]
@g4s8 Please, take a look. This is overall description of the feature. When we will submit the approach, part of it will be moved to corresponded modules

**Comment by g4s8** [comment]
@brastak thanks. Sounds good. I have a few comments:

> When GroupSlice handle requests, it calls in parallel all slices in the list

I don't think it's correct, since user is not able to control the order of underlying repositories to use, we've discussed similar issue here, please take a look: https://github.com/artipie/docker-adapter/issues/160#issuecomment-637532326 We may send all requests simultaneously but process them in user defined order.

> subject to discuss - we can add HTTP HEAD or other "read" methods if they are used by repos

As I remember Docker registry uses `HEAD` requests.

@artipie/contributors does anybody have some comments?

**Comment by 0crat** [comment]
The job [#169](https://github.com/artipie/http/issues/169) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/eac8705e-7c99-42d8-b9e7-d42997cf29c0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@brastak done in #180

**Comment by g4s8** [comment]
@rultor release, tag=`0.11`
