### ISSUE TITLE
Response with status

### ISSUE THREAD

**Issue by g4s8** [artipie/http#17]
Add response to override status line.

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.0`

**Comment by yegor256** [comment]
@g4s8 something is wrong here

**Comment by g4s8** [comment]
@rultor release, tag=`0.1`

**Comment by g4s8** [comment]
Done in #21

**Comment by Guseyn** [comment]
@g4s8 close the ticket! @yegor256 please pay attention to the problem with non closed tickets.

**Comment by 0crat** [comment]
Job `gh:artipie/http#17` is not assigned, can't get performer
