### ISSUE TITLE
Rt rule for any match operation

### ISSUE THREAD

**Issue by Sammers21** [artipie/http#170]
In order to avoid code duplication like the following one:
```java
new SliceRoute(
    new SliceRoute.Path(
        new RtRule.ByMethod(RqMethod.PUT),
        new PushChartSlice(storage)
    ),
    new SliceRoute.Path(
        new RtRule.ByMethod(RqMethod.POST),
        new PushChartSlice(storage)
    )
)
```
when an endpoint could respond to several types of request, I'd like to introduce the `RtRule.Any` rule. By using this rule you could avoid code duplications like the one above and replace them with the one below:

```java
new SliceRoute(
    new SliceRoute.Path(
        new RtRule.Any(
            new RtRule.ByMethod(RqMethod.POST),
            new RtRule.ByMethod(RqMethod.PUT)
        ),
        new PushChartSlice(storage)
    )
)
```

And, as a memory-wise benefit, only one instance of `PushChartSlice` is created.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by Sammers21** [comment]
@g4s8, could you release a new version?

**Comment by g4s8** [comment]
@Sammers21 you can do it by yourself in asto and http modules

**Comment by Sammers21** [comment]
@rultor, release tag=`0.10.0`

**Comment by g4s8** [comment]
@Sammers21 please close this ticket if the problem was solved.

**Comment by 0crat** [comment]
Job `gh:artipie/http#170` is not assigned, can't get performer
