### ISSUE TITLE
Standard headers

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#174]
There are standard HTTP headers which are used across many adapters, such as `Content-Length`, `Content-Type`, `Location`, `WWW-Authenticate` etc. It would be nice to have dedicated classes for such headers.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/http#174` is not assigned, can't get performer

**Comment by olegmoz** [comment]
@rultor release, tag=`0.10.1`

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.10.1`
