### ISSUE TITLE
RsWithBody content-length headers

### ISSUE THREAD

**Issue by g4s8** [artipie/http#176]
Let's add `Content-Length` based on #175 header when sending `RsWithBody` of publisher with known size.
@artipie/contributors FYI

**Comment by 0crat** [comment]
The job [#176](https://github.com/artipie/http/issues/176) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/4e139a41-da21-4f90-9f3e-e580aab799c6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
Done in #177
