### ISSUE TITLE
Default HTTP version in `RequestLine`

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#187]
`RequestLine` requires HTTP version as one of it's constructor parameters. It's very rare to have version other then `HTTP/1.1`, yet it has to specified every time.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/http#187` is not assigned, can't get performer

**Comment by olegmoz** [comment]
@rultor release, tag=`0.12`
