### ISSUE TITLE
Joining headers sets

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#189]
There is no convenient way to join two header sets or add single header to existing headers set. This operation is quite common when implementing authentication, as authentication header(s) required to be added to existing request or response.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/http#189` is not assigned, can't get performer
