### ISSUE TITLE
Support for `Authorization` header

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#191]
`Authorization` header is handled by adapters requiring authentication. Also it is required to handle authentication requests by other HTTP servers for proxy type repositories. Not it is supported only for Basic auth, it should be generalized and supported for Bearer authentication as well

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#194](https://github.com/artipie/http/issues/194) is still not solved.

**Comment by 0crat** [comment]
Job `gh:artipie/http#191` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@olegmoz the only puzzle [#194](https://github.com/artipie/http/issues/194) is solved here.
