### ISSUE TITLE
Authorization.java:34-37: Extract header value parsing...

### ISSUE THREAD

**Issue by 0pdd** [artipie/http#194]
The puzzle `191-868754ef` from #191 has to be resolved: 

https://github.com/artipie/http/blob/eec2ba77a2ccc115df8014f7c0b44bfacf4614b9/src/main/java/com/artipie/http/headers/Authorization.java#L34-L37

The puzzle was created by @olegmoz on 02-Jul-20. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue
