### ISSUE TITLE
Status code classification in `RsStatus`

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#196]
[RFC](https://tools.ietf.org/html/rfc7231) breaks down codes into categories by first digit. It would be useful to have these categories in `RsStatus`. For example we may have methods like `bool clientError()` for 4xx, `bool serverError()` for 5xx and `bool error() { return clientError() || serverError(); }`.

Originated in https://github.com/artipie/artipie/pull/283#discussion_r451498806

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by g4s8** [comment]
@olegmoz sounds reasonable

**Comment by g4s8** [comment]
@rultor release, tag=`0.15.6`

**Comment by 0crat** [comment]
Job `gh:artipie/http#196` is not assigned, can't get performer
