### ISSUE TITLE
TrimPathSlice may remove path twice in case of group repositories

### ISSUE THREAD

**Issue by g4s8** [artipie/http#197]
Let's check for `X-FullPath` and ignore such requests which were already trimmed.

**Comment by 0crat** [comment]
The job [#197](https://github.com/artipie/http/issues/197) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/832d36d9-cf08-4f0f-b400-bc989b8b4c50); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.14`

**Comment by g4s8** [comment]
@rultor release, tag=`0.14.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.14.2`

**Comment by g4s8** [comment]
Fixed
