### ISSUE TITLE
Class to obtain resource

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/http#208]
I'd suggest to introduce class to obtain resource from `getContextClassLoader` in `com.artipie.http.hm` as almost every adapter uses some test resources in tests.

**Comment by olenagerasimova** [comment]
@g4s8 what do you say?

**Comment by olenagerasimova** [comment]
We'll do in `asto`

**Comment by 0crat** [comment]
Job `gh:artipie/http#208` is not assigned, can't get performer
