### ISSUE TITLE
Better headers types in `RsHasHeaders` and `ResponseMatcher`

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#214]
`RsHasHeaders` accepts only `Collection` of headers in constructor and does not accept `Iterable` - it does not make it compatible with `Headers` interfaces which is widely used.
`ResponseMatcher` does not has constructors supporting headers as `Iterable`, only arrays are accepted. This again makes it unusable in some cases

**Comment by olegmoz** [comment]
@rultor release, tag=`0.15.5`

**Comment by 0crat** [comment]
Job `gh:artipie/http#214` is not assigned, can't get performer
