### ISSUE TITLE
SliceDelete.java:38-41: Implement SliceDelete Implement...

### ISSUE THREAD

**Issue by 0pdd** [artipie/http#218]
The puzzle `138-96915975` from #138 has to be resolved: 

https://github.com/artipie/http/blob/6bd649be9b5244ee8ff94dbbe3c70a99dea09610/src/main/java/com/artipie/http/slice/SliceDelete.java#L38-L41

The puzzle was created by paulodamaso on 12-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `138-96915975` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 26 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
