### ISSUE TITLE
Authentication composition

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#222]
Multiple `Authentication` instances might be joined into single `Authentication` that delegates to others. In production it might be composition of different authentication methods. It is also useful in tests to join several `Authentication.Single` instances to have `Authentication` allowing more then one user

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/http#222` is not assigned, can't get performer

**Comment by olegmoz** [comment]
@rultor release, tag=`0.15.7`
