### ISSUE TITLE
Keep dependencies up-to-date

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#236]
The module has multiple dependencies, they need to be kept up-to-date

**Comment by olegmoz** [comment]
@rultor release, tag=`0.15.8`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.15.8`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.15.8`

**Comment by g4s8** [comment]
Added dependabot config
