### ISSUE TITLE
Create interface for permission action

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/http#238]
Part of https://github.com/artipie/artipie/issues/574:
1. Create interface for permission action and synonyms, implementations for permissions `READ` and `WRITE`, create class to obtain this interface instance by any string synonym
2. Change `Permission.ByName` string action field to interface and add new ctor, use a set of synonyms to call `Permissions#allowed` with from the `Permission.ByName#allowed`

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) resigned from [#238](https://github.com/artipie/http/issues/238), since the job is not in scope anymore
