### ISSUE TITLE
RequestLineFrom.java:103-105: Check idx value to avoid...

### ISSUE THREAD

**Issue by 0pdd** [artipie/http#24]
The puzzle `12-587fa439` from #12 has to be resolved: 

https://github.com/artipie/http/blob/8e05d2ac38112e06735dc4c21b1dff7f83d69623/src/main/java/com/artipie/http/rq/RequestLineFrom.java#L103-L105

The puzzle was created by @g4s8 on 06-Feb-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by olenagerasimova** [comment]
@0crat assign @olenagerasimova

**Comment by 0crat** [comment]
> @0crat assign @olenagerasimova  ([here](https://github.com/artipie/http/issues/24#issuecomment-614203692))

@olenagerasimova You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) are: `REV`, `DEV`

**Comment by 0crat** [comment]
The job [#24](https://github.com/artipie/http/issues/24) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f37d3417-5fa8-49fe-ac84-d2206816b9c7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `12-587fa439` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job was finished in 28 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by sereshqua** [comment]
@0crat quality good
