### ISSUE TITLE
User groups

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/http#241]
Part of https://github.com/artipie/artipie/issues/573

We need to create `User` class with `username` and `groups` and change `Authentication#user` signature to return optional of this new `User` class.

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.11`

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.16`

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.16`

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.16.1`
