### ISSUE TITLE
Change auth interfaces signature

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/http#244]
Change signature of `Identities`, `Permission` and `Permissions` interfaces to work with `Authentication.User` class interad of just user name.

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.16.2`

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) resigned from [#244](https://github.com/artipie/http/issues/244), since the job is not in scope anymore
