### ISSUE TITLE
Creare `BasicAuthSlice`

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/http#247]
Let's create `BasicAuthSlice` to john `SliceAuth` and `BasicIdentities` functionality and deprecate `SliceAuth`, `Identities` and `BasicIdentities`.

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) resigned from [#247](https://github.com/artipie/http/issues/247), since the job is not in scope anymore

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.16.3`
