### ISSUE TITLE
Create Authentication.Anonymous 

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/http#249]
Let's create `Authentication.Anonymous` implementation to use when auth is not required.

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.16.4`

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) resigned from [#249](https://github.com/artipie/http/issues/249), since the job is not in scope anymore
