### ISSUE TITLE
StatefulResponse finishes send before body is read

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#251]
`StatefulResponse` returns completed future from it's `send()` method before it reads body. By contract body publisher not guaranteed to be readable after send is finished, because sending reply may wish to dispose allocated resources. `StatefulResponse` should be fixed to be compatible with all responses, including responses producing one-time content publishers such as HTTP client responses.

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by olegmoz** [comment]
@rultor release, tag=`0.16.5`

**Comment by 0crat** [comment]
Job `gh:artipie/http#251` is not assigned, can't get performer
