### ISSUE TITLE
Create RtRule.ByHeader implementation 

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/http#253]
In pypi-adapter `RtRule` by header is required, so let's create such implementation. Implementation should filter requests by header name and value, it should be possible to filter values by regexps.

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it

**Comment by olenagerasimova** [comment]
@rultor release, tag=`16.6`

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.16.6`

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it
