### ISSUE TITLE
Handling errors in GroupSlice

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#256]
`GroupSlice` does not send response when origin `Slice` fails to send response. This causes `GroupSlice` requests to never complete

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by olegmoz** [comment]
@rultor release, tag=`0.16.7`

**Comment by 0crat** [comment]
Job `gh:artipie/http#256` is not assigned, can't get performer
