### ISSUE TITLE
Permission that requires other permissions

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#258]
It would be nice to have `Permission` implementation that joins multiple other `Permission` instances and allows action only when all other `Permission` instances allow the action

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by olegmoz** [comment]
@rultor release, tag=`0.16.8`

**Comment by 0crat** [comment]
Job `gh:artipie/http#258` is not assigned, can't get performer
