### ISSUE TITLE
Stop Releasing From Different Tickets!

### ISSUE THREAD

**Issue by amihaiemil** [artipie/http#26]
I am watching these repos and I noticed you guys are telling rultor to ``release`` from all over the place (in different Issues and PRs).

It's better to make a new Issue for each release and inside its description the releaser should describe what does the release contain. 

If you do it chaotically, nobody will be able to tell which release contains which feature.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@g4s8 @yegor256 @Sammers21 Please read this.

**Comment by Sammers21** [comment]
> If you do it chaotically, nobody will be able to tell which release contains which feature.

Rultor publish the release logs, that is not a problem

**Comment by amihaiemil** [comment]
@Sammers21 It's not the same thing. The Rultor Log might display 50 different commits with possibly poor commit messages. It's better if someone makes a short summary with a few bullet points...

**Comment by Guseyn** [comment]
@amihaiemil completely agree + we need close issues in time as it's difficult to follow what's done and what's not.

**Comment by g4s8** [comment]
@amihaiemil I think it's OK to release some new feature right from the ticket. For instance, you have a ticket "Logging slice" and when you release from the same ticket, it's clear that you're making a release to introduce new logging implementation. We are releasing quite often, sometimes it's few times a day, I think it would be an overhead to create release tickets for small releases.

**Comment by 0crat** [comment]
Job `gh:artipie/http#26` is not assigned, can't get performer
