### ISSUE TITLE
Move RsJson from artipie

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/http#260]
Let's move `RsJson` from artipie to http, this class is used all over artipie and can be useful in adapters.

**Comment by olenagerasimova** [comment]
alrady done

**Comment by 0crat** [comment]
Job [#260](https://github.com/artipie/http/issues/260) is closed, can't start order

**Comment by 0crat** [comment]
Job `gh:artipie/http#260` is not assigned, can't get performer
