### ISSUE TITLE
RsWithBody and RsFull lack constructor for Content

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#275]
`RsWithBody` lacks constructor with just `Content` provided. This causes code like `new RsWithBody(new Content(...))` code to invoke constructor `RsWithBody(Publisher)` and loose size of content on the way. Same problem presents in `RsFull` as it's constructor accepts `Publisher` only.

**Comment by olegmoz** [comment]
@rultor release, tag=`0.17.6`

**Comment by 0crat** [comment]
Job `gh:artipie/http#275` is not assigned, can't get performer
