### ISSUE TITLE
Token based authentication

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/http#371]
Anaconda repository uses token based authentication mechanism, so we need to support such authentication. Repository [uses](https://docs.anaconda.com/anacondaorg/user-guide/tasks/work-with-accounts/#cloud-accounts-tokens) random alphanumeric string with one year expire period.

**Comment by olenagerasimova** [comment]
@g4s8 could you please take a look? Any ideas for general implementation? We need to store the tokens somewhere (in storage more likely) and choose an algorithm to generate tokens.

**Comment by g4s8** [comment]
@olenagerasimova I think we can change implementation of `com.artipie.http.auth.AuthScheme` which is accepting only request headers now to get authentication result. For Conda we should check request line too. So `AuthScheme` interface can accept not only headers but request line to get the user.

Then, we can implement `Authentication` interface for Conda which accepts only token and return user if found for token.

And finally, it could be joined by `AuthSlice` in Conda adapter.

---

As I see in Conda [documentation](https://docs.anaconda.com/anacondaorg/user-guide/tasks/work-with-accounts/#cloud-accounts-tokens), tokens are generated by some administrators there, so it's logically to store them in the same place as other authentication credentials - `_credentials.yaml`.

WDYT?

**Comment by olenagerasimova** [comment]
@g4s8 thanks, sounds logical. The only part I cannot get is about storing the tokens: documentation shows anaconda interface where users (and administrators) can manage tokens, but creating token manually (by user itself or administrator) is not required, anaconda can (and so should artipie) generate user token automatically. 
We have access to `_credentials.yaml` only on artipie/artipie level now, how do we write new tokens there?

**Comment by g4s8** [comment]
@olenagerasimova it's not clear, where exactly a new token should be created? On what level and what operation

**Comment by olenagerasimova** [comment]
@g4s8 token should be created on repository server (anaconda/artipie) side, here is some [doc](https://api.anaconda.org/docs#/authentication/post_authentications) (not very informative) and logs:
```
[DEBUG] vert.x-eventloop-thread-1 com.artipie.conda.BodyLoggingSlice: >> POST /authentications HTTP_1_1

Host: host.testcontainers.internal:61246
User-Agent: Anaconda-Client/1.8.0 (+https://anaconda.org)
Accept-Encoding: gzip, deflate
Accept: application/json
Connection: keep-alive
x-binstar-api-version: 1.8.0
Content-Type: application/json
Content-Length: 245
Authorization: Basic YW55OmFueQ==
```

Request body (we just ignore it):
```json
{"scopes": null, "note": "binstar_client:root@886f35ed479f", "note_url": "http://host.testcontainers.internal:61246/", "hostname": "886f35ed479f", "user": null, "max-age": null, "created_with": null, "strength": "strong", "fail-if-exists": true}
```

Response body:
```json
{ "token", "ol-4ee312d8-9fe2-44d2-bea9-053325e1ffd5" }
```

This request is sent when `anaconda login` command is performed.

Also, about implementation: I think it would be better to implement `AuthScheme` for conda in the adapter, not here. To get user by token we can implement `TokenAuthentication` interface, maybe also in the adapter.

**Comment by g4s8** [comment]
@olenagerasimova I see, so the main questions: what is the scope of these tokens? Can we use a single token for accessing different repositories, or it's one token per repository/organization? If it's not global (one token for all Artipie repos) then we can keep it inside repositories and not in `_credentials.yml`

**Comment by olenagerasimova** [comment]
@g4s8 on the artipie side scope is managed by repository permissions, so I guess the real question is do we want to build correspondence between our own permissions and these tokens. I think it's not necessary now, we can add single token per user or single token per user in the repository. Second option seams more flexible and more adaptable for the scopes (if they will be required ever). 

Note, that with tokens packages can be downloaded by anyone, how has the link containing the token, for example: `/t/token/my-conda/my-package.conda`

**Comment by olenagerasimova** [comment]
done
