### ISSUE TITLE
Create constants for HTTP values

### ISSUE THREAD

**Issue by paulodamaso** [artipie/http#38]
It would be a good idea to create constants to HTTP values, for example:
- HTTP_OK = 200
- HTTP_NOT_FOUND = 404
- HTTP_METHOD_GET = "GET"
- HTTP_METHOD_POST = "POST"
And so on. Then, these constants would be used in all other projects, getting rid of all the magic numbers we currently have both in code and tests

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by Gitboy-7** [comment]
10gb****data### boundle

**Comment by olegmoz** [comment]
The issue is resolved: we have got `RqMethod` and `RsStatus` classes with constants from RFC

**Comment by 0crat** [comment]
Job `gh:artipie/http#38` is not assigned, can't get performer
