### ISSUE TITLE
Move Slice for handling HEAD requests from files-adapter

### ISSUE THREAD

**Issue by g4s8** [artipie/http#397]
Move `Slice` implementation for handling `HEAD` HTTP requests from artipie/files-adapter here, make it more flexible to add additional data to response headers which may be needed for concrete adapters implementation (e.g. maven-adapter appends checksums for HEAD requests of artifacts)

_Originally posted by @olenagerasimova in https://github.com/artipie/files-adapter/pull/79#discussion_r737157273_

**Comment by g4s8** [comment]
> @g4s8 wouldn't it be better to wait for the outcome of the discussion at [artipie/asto#346](https://github.com/artipie/asto/issues/346) to judge if it is appropriate to make this class more flexible in terms of adding additional data to response headers (cause we will be able to do it internally) ? WDYT ?

@baudoliver7 I think we can update this `Slice` when artipie/asto#346 is done to change default behavior, but  artipie/asto#346 doesn't cover some special cases for some adapters, so we need to design it as flexible to be able to append some metadata in repositories without creating a new slice.

**Comment by baudoliver7** [comment]
@g4s8 Ok

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#400](https://github.com/artipie/http/issues/400) is still not solved.
