### ISSUE TITLE
Implement GzipSlice

### ISSUE THREAD

**Issue by g4s8** [artipie/http#404]
Add a new `Slice` implementation that checks that request `Accept-Encoding` header contains `gzip` value, e.g.: `Accept-Encoding: gzip` and compress output body with gzip and adds `Content-Encoding: gzip` header.

Headers docs: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding
Required for: artipie/git-adapter#1

**Comment by olenagerasimova** [comment]
@g4s8 it seems that it would be better to perform header checking on the upper level with the help of `RtRule.ByHeader`, not in the new `GzipSlice`. What do you say?

**Comment by g4s8** [comment]
> 

@olenagerasimova `RtRule.ByHeader` is just a routing rule, but gzip compression here is a part of content-negotiation: if client support gzip content (send `accept-encoding` header), then server compress it; but if client doesn't support it, then server returns uncompressed response body.

**Comment by olenagerasimova** [comment]
@g4s8 the content-negotiation logic can be handled with the help of the rules on the adapter level
```
new SliceRoute(
    RtRule.ByHeader("accept-encoding", ".*gzip.*"),
    new GzipSlicee()
),
new SliceRoute(
    RtRule.ByMethod(RqMethod.GET),
    new DownloadSlice()
),
```
Thus, `GzipSlice` will gzip the content and add `Content-Encoding: gzip` header, download slice will return content as is. Otherwise, we will duplicate the logic of `DownloadSlice` in the `GzipSlice`, which does not seem necessary.

**Comment by g4s8** [comment]
> @g4s8 the content-negotiation logic can be handled with the help of the rules on the adapter level
> 
> ```
> new SliceRoute(
>     RtRule.ByHeader("accept-encoding", ".*gzip.*"),
>     new GzipSlicee()
> ),
> new SliceRoute(
>     RtRule.ByMethod(RqMethod.GET),
>     new DownloadSlice()
> ),
> ```
> 
> Thus, `GzipSlice` will gzip the content and add `Content-Encoding: gzip` header, download slice will return content as is. Otherwise, we will duplicate the logic of `DownloadSlice` in the `GzipSlice`, which does not seem necessary.

@olenagerasimova but it'll be a lot of boilerplate code, since gzip encoding can be used **only if** client sends `accept-encoding: gzip`, and there are no valid scenarios to use it without content-negotiation.

So to keep classes simple, maybe we can introduce 2 classes: package-private `GzipSlice` (private to avoid incorrect usage by clients), and public `Slice` entry point with simple routing like you suggested:
```java
// assuming GzipSlice just compress output wiht gzip
public WithGzip extends Slice.Wrap {
  public WithGzip(Slice origin) {
    super(
      new SliceRoute(
        new RtRulePath(
          RtRule.ByHeader("accept-encoding", ".*gzip.*"), // if client accept gzip encoding
          new GzipSlice(origin) // compress origin's response body
        ),
        new RtRulePath(
          RtRule.FALLBACK, // if not accept
          origin // just return plain reponse
        )
      )
    );
  }
}  
```
WDYT?
