### ISSUE TITLE
Async implementations with exception handling

### ISSUE THREAD

**Issue by g4s8** [artipie/http#41]
Move `Async*` implementations from https://github.com/artipie/artipie/issues/27
to this module and implement exception handling for `CompletableStage` of responses and slices. In case of unhandled error state in `CompletionStage` we should return HTTP response with 500 status code.

**Comment by 0crat** [comment]
The job [#41](https://github.com/artipie/http/issues/41) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/0ed58f98-9ba7-4a16-af67-28d7e37b7352); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#59](https://github.com/artipie/http/issues/59) is still not solved.

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.1`

**Comment by g4s8** [comment]
@rultor stop

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.1`

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#59](https://github.com/artipie/http/issues/59) is solved here.

**Comment by 0crat** [comment]
Job `gh:artipie/http#41` is not assigned, can't get performer
