### ISSUE TITLE
Parse request line query parameter list

### ISSUE THREAD

**Issue by g4s8** [artipie/http#413]
`RqParams` class returns `Optional<String>` for query parameters assuming that HTTP request line URI contains only one query param value for name. But  actually it may have many params with same name and different values. Let's add additional method to get all parameters for `RqParams`: `List<? extends String> values(String name)`

_Originally posted by @baudoliver7 in https://github.com/artipie/artipie/pull/979#r774647115_

**Comment by g4s8** [comment]
@Yuurga thanks for fixing this! @baudoliver7 the problem you've found was solved.

**Comment by baudoliver7** [comment]
@Yuurga Ah, I see now. I was wrong. I put the wrong value, sorry.

**Comment by baudoliver7** [comment]
> @baudoliver7, I assumed that the input (query) is a string with parameters only, i.e. already cut after '?'.

@Yuurga Ah, I see now. I was wrong. I put the wrong value, sorry.

**Comment by g4s8** [comment]
@baudoliver7 @Yuurga `<? extends String>` is used here to make this list readonly: users won't be able to add or insert something due to compilation error
