### ISSUE TITLE
package-info.java:28-32: Implements TkResponse class. It...

### ISSUE THREAD

**Issue by 0pdd** [artipie/http#5]
The puzzle `3-7995f123` from #3 has to be resolved: 

https://github.com/artipie/http/blob/661805a6d7f756d7fac34ffc5bb5544816d197dc/src/main/java/com/artipie/http/tk/package-info.java#L28-L32

The puzzle was created by @g4s8 on 03-Feb-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@a89d63b9d9d0, thread: pool-768-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to artipie/http#5: @g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue
```

[0.51.0](https://github.com/zerocracy/farm): Issue: artipie/http#5, Action: `opened`

**Comment by 0crat** [comment]
The job [#5](https://github.com/artipie/http/issues/5) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/2f1d8c27-c91e-4eba-84b3-7c5b8eb15dcf); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `3-7995f123` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#5](https://github.com/artipie/http/issues/5), since the job is not in scope anymore

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@706b9e63c3bc, thread: PQ-CT2E6TK9B
com.zerocracy.claims.ClaimIn[214] java.lang.IllegalArgumentException: Parameter "age" not found in "Order was canceled" among: [reason, priority, job, cause, _parent_sig, flow, voluntarily, login]
```

[0.51.6](https://github.com/zerocracy/farm): CID: [75f9feba-4127-4488-944b-ad23277ec4b3](https://www.0crat.com/footprint/CT2E6TK9B/75f9feba-4127-4488-944b-ad23277ec4b3), Type: "Order was canceled"
