### ISSUE TITLE
AsyncSlice.java:41-44: Add unit tests for AsyncSlice and...

### ISSUE THREAD

**Issue by 0pdd** [artipie/http#59]
The puzzle `41-f448a190` from #41 has to be resolved: 

https://github.com/artipie/http/blob/612eb5835c4b3ce8b80061532741cba5f0aa308e/src/main/java/com/artipie/http/async/AsyncSlice.java#L41-L44

The puzzle was created by @g4s8 on 19-Feb-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/http#59` is not assigned, can't get performer
