### ISSUE TITLE
'Response' class is synchronous by design

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#61]
Right now 'RsAsync' is async implementation of 'Response'. However 'Response' interface is synchronous by design, it's `send()` method returns `void`, so for caller of 'send()' method it is impossible to tell when `Response` has sent itself to connection.
After discussion with @g4s8 we decided to make `Response.send()` method async.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@rultor release, tag=`0.5`

**Comment by 0crat** [comment]
Job `gh:artipie/http#61` is not assigned, can't get performer
