### ISSUE TITLE
Serve files from storage by key as a path

### ISSUE THREAD

**Issue by g4s8** [artipie/http#64]
Add `Slice`s to upload and download data from `Storage` by `Key` from path of request URI

**Comment by 0crat** [comment]
The job [#64](https://github.com/artipie/http/issues/64) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/449656da-8165-4019-ba8d-6c8badb3c1a9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.6`

**Comment by g4s8** [comment]
@rultor release, tag=`0.6`

**Comment by g4s8** [comment]
@rultor release, tag=`0.6.1`

**Comment by g4s8** [comment]
Done in #65
