### ISSUE TITLE
ByteByByteSplit.java:43-45: Thread safety improvements....

### ISSUE THREAD

**Issue by 0pdd** [artipie/http#67]
The puzzle `32-0fde6650` from #32 has to be resolved: 

https://github.com/artipie/http/blob/5b955ad486f2a340e590e9d04142040d1ffe9fee/src/main/java/com/artipie/http/stream/ByteByByteSplit.java#L43-L45

The puzzle was created by @Sammers21 on 05-Mar-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/http#67` is not assigned, can't get performer
