### ISSUE TITLE
TkRequest.java:83-89: Implement this class. It should...

### ISSUE THREAD

**Issue by 0pdd** [artipie/http#7]
The puzzle `3-21935464` from #3 has to be resolved: 

https://github.com/artipie/http/blob/661805a6d7f756d7fac34ffc5bb5544816d197dc/src/main/java/com/artipie/http/tk/TkRequest.java#L83-L89

The puzzle was created by @g4s8 on 03-Feb-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@a89d63b9d9d0, thread: pool-778-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to artipie/http#7: @g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue
```

[0.51.0](https://github.com/zerocracy/farm): Issue: artipie/http#7, Action: `opened`

**Comment by 0crat** [comment]
The job [#7](https://github.com/artipie/http/issues/7) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/3cbb73b6-b0fd-4bab-8a54-355f7b1b71b9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `3-21935464` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#11](https://github.com/artipie/http/issues/11) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 24 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#11](https://github.com/artipie/http/issues/11) is solved here.
