### ISSUE TITLE
SliceRoute.java:57-59: Refactor SliceRoute to get rid of...

### ISSUE THREAD

**Issue by 0pdd** [artipie/http#72]
The puzzle `51-aa5d6442` from #51 has to be resolved: 

https://github.com/artipie/http/blob/a0205804215e932e9f37efd57e185a1cd0f9634c/src/main/java/com/artipie/http/rt/SliceRoute.java#L57-L59

The puzzle was created by @g4s8 on 11-Mar-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#72](https://github.com/artipie/http/issues/72) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/d6e42c05-58ca-4d17-9e47-041bc5085aea); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `51-aa5d6442` has disappeared from the source code, that's why I closed this issue.
