### ISSUE TITLE
Few minor features

### ISSUE THREAD

**Issue by g4s8** [artipie/http#73]
Add `Slice` implementation for static response object, e.g. `new SliceSimple(new RsWithStatus(200))`

Add default decorator of `Slice`, e.g. `new Slice.Wrap(slice)` to help with constructing new slices.

Add `RtRule` to accept any request to be used as a fallback option.

**Comment by g4s8** [comment]
@rultor release, tag=`0.7`

**Comment by g4s8** [comment]
@Guseyn fixed in #79 #80 #81

**Comment by 0crat** [comment]
Job `gh:artipie/http#73` is not assigned, can't get performer
