### ISSUE TITLE
Support RqMethod in RtRule.ByMethod

### ISSUE THREAD

**Issue by g4s8** [artipie/http#85]
Let's accept `RqMethod` values in `RtRule.ByMethod` constructor instead of strings. We can keep strings constructor as well but mark is as deprecated.

**Comment by g4s8** [comment]
@rultor release, tag=`0.7.1`

**Comment by 0crat** [comment]
The job [#85](https://github.com/artipie/http/issues/85) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/dbb9572a-301e-44b2-a927-a41eecf41fe4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.7.1`

**Comment by Guseyn** [comment]
@g4s8 close completed tickets
