### ISSUE TITLE
Multipart.java:48-51: Finish implementation. In order to...

### ISSUE THREAD

**Issue by 0pdd** [artipie/http#90]
The puzzle `32-8c776bfe` from #32 has to be resolved: 

https://github.com/artipie/http/blob/16bfad340ea584590ad982844710bdc96e398f27/src/main/java/com/artipie/http/rq/Multipart.java#L48-L51

The puzzle was created by @Sammers21 on 19-Mar-20. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@Sammers21 do you want to complete multipart parsing implementation?

**Comment by 0crat** [comment]
The job [#90](https://github.com/artipie/http/issues/90) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/4ca708c4-1ab0-4791-940e-85602efb3f7f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @sammers21[/z](https://www.0crat.com/u/sammers21) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by g4s8** [comment]
@Sammers21 please pay attention to all multipart issues

**Comment by 0crat** [comment]
@sammers21[/z](https://www.0crat.com/u/sammers21) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @sammers21[/z](https://www.0crat.com/u/sammers21) resigned from [#90](https://github.com/artipie/http/issues/90), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#90](https://github.com/artipie/http/issues/90) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/d31ff69d-de04-412a-85d3-1c720c090ae6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/http/issues/90#issuecomment-644889317))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#90](https://github.com/artipie/http/issues/90), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/http/issues/90#issuecomment-644889317))

@victornoel Job refused in 7 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#90](https://github.com/artipie/http/issues/90) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/564a0e9c-2e58-4fa7-abd6-8b04e54e1097); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/http/issues/90#issuecomment-645566153))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#90](https://github.com/artipie/http/issues/90), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/http/issues/90#issuecomment-645566153))

@paulodamaso Job refused in 22 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#90](https://github.com/artipie/http/issues/90) assigned to @iakunin[/z](https://www.0crat.com/u/iakunin), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/05c780b6-9273-423f-93ef-19a0d4905079); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @iakunin[/z](https://www.0crat.com/u/iakunin) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
@iakunin[/z](https://www.0crat.com/u/iakunin) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by iakunin** [comment]
@0crat wait for https://github.com/artipie/http/issues/95 to be completed, cause it requires [here](https://github.com/artipie/http/blob/ee5085b91259110d16b23970958f5c603b9a52c2/src/main/java/com/artipie/http/rq/Multipart.java#L103).

**Comment by iakunin** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/http/issues/90#issuecomment-650800641))

@iakunin This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#90](https://github.com/artipie/http/issues/90) is [in scope](http://www.zerocracy.com/policy.html#14) for 24days
  * The role is `DEV`
  * The job is assigned to @iakunin[/z](https://www.0crat.com/u/iakunin) for [6days](http://www.zerocracy.com/policy.html#8)
  * @iakunin[/z](https://www.0crat.com/u/iakunin) is on vacation!
  * There is a monetary reward attached
  * @iakunin[/z](https://www.0crat.com/u/iakunin) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @sammers21[/z](https://www.0crat.com/u/sammers21): User was resigned from the ticket
    * @victornoel[/z](https://www.0crat.com/u/victornoel): User was resigned from the ticket
    * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fhttp%2390%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
