### ISSUE TITLE
Add convinient response matchers

### ISSUE THREAD

**Issue by olegmoz** [artipie/http#93]
It is common to check that response body is a string with particular content or JSON.
From this discussion: https://github.com/artipie/nuget-adapter/pull/62#discussion_r397872069

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/http#93` is not assigned, can't get performer
