### ISSUE TITLE
PartFromPublisher.java:34-36: Implement delyaed publisher...

### ISSUE THREAD

**Issue by 0pdd** [artipie/http#95]
The puzzle `32-9bb15c22` from #32 has to be resolved: 

https://github.com/artipie/http/blob/3b00f0945bf8776a1b412de0d36e637fdcca2050/src/main/java/com/artipie/http/rq/PartFromPublisher.java#L34-L36

The puzzle was created by @Sammers21 on 24-Mar-20. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#95](https://github.com/artipie/http/issues/95) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/778f5e71-ab4d-445d-b070-e2f20a0c2fc7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @sammers21[/z](https://www.0crat.com/u/sammers21) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@sammers21[/z](https://www.0crat.com/u/sammers21) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @sammers21[/z](https://www.0crat.com/u/sammers21) resigned from [#95](https://github.com/artipie/http/issues/95), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#95](https://github.com/artipie/http/issues/95) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/af7de658-567b-41f4-822f-7948dd91024d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/http/issues/95#issuecomment-609456379))

@ammaratef45 The user @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) resigned from [#95](https://github.com/artipie/http/issues/95), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/http/issues/95#issuecomment-609456379))

@ammaratef45 Job refused in 3 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#95](https://github.com/artipie/http/issues/95) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/9e3c1ad3-b995-4dca-bf24-5a24adb06494); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/http/issues/95#issuecomment-609469891))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#95](https://github.com/artipie/http/issues/95), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/http/issues/95#issuecomment-609469891))

@victornoel Job refused in 0 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#95](https://github.com/artipie/http/issues/95) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/0d16791a-b9d4-403b-990d-1fe02c39e3c6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/http/issues/95#issuecomment-610068200))

@carlosmiranda Job refused in 21 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/http/issues/95#issuecomment-610068200))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#95](https://github.com/artipie/http/issues/95), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#95](https://github.com/artipie/http/issues/95) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/c621bf03-5c12-40a7-b70e-fbbc91542273); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@g4s8 This puzzle is confusing. Should I continue to implement `PartFromPublisher` and activate `ableToParseBasic` test on `MultipartTest`? If yes, how I'm supposed to discover the headers from `publisher`? Tried to get some info on #32, but there is no description also

**Comment by paulodamaso** [comment]
@g4s8 ping

**Comment by paulodamaso** [comment]
@0crat wait for answer

**Comment by g4s8** [comment]
@paulodamaso I think it's not relevant right now and can be suspended for some time

**Comment by g4s8** [comment]
@0crat refuse

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/http/issues/95#issuecomment-625673210))

@g4s8 The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#95](https://github.com/artipie/http/issues/95), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/http/issues/95#issuecomment-625673232))

@g4s8 Job `gh:artipie/http#95` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#95](https://github.com/artipie/http/issues/95) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/5369ef15-994d-4239-9048-f5ce82838341); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @sammers21[/z](https://www.0crat.com/u/sammers21) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
The user @sammers21[/z](https://www.0crat.com/u/sammers21) resigned from [#95](https://github.com/artipie/http/issues/95), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@69479bfe-25b6-466a-835a-a020547757e2, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:artipie/http#95] declared for identity constraint of element "speed".
```

[0.53.15](https://github.com/zerocracy/farm): CID: [5a4aafa4-94b4-46c3-9e3b-1f93753fb355](https://www.0crat.com/footprint/CT2E6TK9B/5a4aafa4-94b4-46c3-9e3b-1f93753fb355), Type: "Order was canceled"

**Comment by 0crat** [comment]
The job [#95](https://github.com/artipie/http/issues/95) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/3e229ce9-5282-464c-95e3-8e69350b6bf4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/http/issues/95#issuecomment-644889209))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#95](https://github.com/artipie/http/issues/95), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/http/issues/95#issuecomment-644889209))

@victornoel Job refused in 8 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/http/issues/95#issuecomment-644889209))

@victornoel There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@abb255a1-bcf3-4f3a-b309-45c684d4eb9c, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:artipie/http#95] declared for identity constraint of element "speed".
```

[0.53.15](https://github.com/zerocracy/farm): CID: [7a8c53e6-bc5f-4dd2-8312-4a32c392cfd9](https://www.0crat.com/footprint/CT2E6TK9B/7a8c53e6-bc5f-4dd2-8312-4a32c392cfd9), Type: "Order was canceled"

**Comment by 0crat** [comment]
The job [#95](https://github.com/artipie/http/issues/95) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/c9697ba1-979a-4962-be9b-2649347da6e1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/http/issues/95#issuecomment-670525872))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#95](https://github.com/artipie/http/issues/95), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/http/issues/95#issuecomment-670525872))

@paulodamaso There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@0d18bf93-b32a-4c79-92cc-94679f50e1c8, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:artipie/http#95] declared for identity constraint of element "speed".
```

[0.54.5](https://github.com/zerocracy/farm): CID: [3edc5bbf-ff56-4841-bbf7-e2fd8d63dc0d](https://www.0crat.com/footprint/CT2E6TK9B/3edc5bbf-ff56-4841-bbf7-e2fd8d63dc0d), Type: "Order was canceled"

**Comment by 0pdd** [comment]
The puzzle `32-9bb15c22` has disappeared from the source code, that's why I closed this issue.
